version: '3.9'
services:
  db-local:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: signalements
      POSTGRES_USER: signal_user
      POSTGRES_PASSWORD: signal_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U signal_user -d signalements"]
      interval: 10s
      timeout: 5s
      retries: 5

  tileserver:
    image: maptiler/tileserver-gl:v4.4.0
    restart: always
    ports:
      - "8083:8080"
    volumes:
      - ./tiles/antananarivo:/data

  app-java:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      db-local:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-local:5432/signalements
      SPRING_DATASOURCE_USERNAME: signal_user
      SPRING_DATASOURCE_PASSWORD: signal_pass
      TILESERVER_URL: http://tileserver:8080
    volumes:
      - ./logs:/app/logs  # Optionnel pour logs

  web-manager:
    build:
      context: ./web-manager
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - app-java
      - tileserver

volumes:
  postgres_data:
